name: Build Branded RustDesk Client

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-2022
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Clone original RustDesk
        shell: powershell
        run: |
          git clone --depth 1 https://github.com rustdesk-source
          Copy-Item -Path "${{ github.workspace }}\build_custom.ps1" -Destination "${{ github.workspace }}\rustdesk-source\build_custom.ps1" -Force
          Copy-Item -Path "${{ github.workspace }}\icon.ico" -Destination "${{ github.workspace }}\rustdesk-source\icon.ico" -Force

      - name: Run Build Script
        working-directory: ./rustdesk-source
        env:
          RENDEZVOUS_SERVER: ${{ secrets.ID_SERVER }}
          RS_PUB_KEY: ${{ secrets.SERVER_KEY }}
        shell: powershell
        run: |
          ./build_custom.ps1 -flutter -portable

      - name: Upload Finished Client
        uses: actions/upload-artifact@v4
        with:
          name: branded-rustdesk-windows
          path: rustdesk-source/target/release/*.exe

